apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hackathon-app
  template:
    metadata:
      labels:
        app: hackathon-app
    spec:
      containers:
      - name: hackathon-app
        image: 736722722555.dkr.ecr.ap-south-1.amazonaws.com/hackathon-app:bc138bab1a72505bb5f77027e532c461ea6c86c
        ports:
        - containerPort: 8080
